#!/bin/bash 

## Alias

# Navigation

alias ..="cd .."
alias ..2="cd ../.."
alias ..3="cd ../../.."
alias ..4="cd ../../../.."
alias ..5="cd ../../../../.."

# Directories

alias rmr="rm -r"

# Ls

alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# Git

alias gs='git stat '
alias gg='git graph '
alias ga='git add '
alias gb='git branch '
alias gc='git commit'
alias gd='git diff'
alias gk='gitk --all&'
alias gx='gitx --all'
alias gpom='git push origin master'

# Color

if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# Tree

alias otree='/usr/bin/tree'
alias tree='otree -aI "__pycache__|.git"'
